### ISSUE TITLE
Is Writer going to work with macOS Sierra

### ISSUE THREAD

**Issue by zenashopson** [HendrikNoeller/Writer#10]
Is Writer going to work with macOS Sierra

**Comment by HendrikNoeller** [comment]
I have not upgraded myself, so I dont know - yet I did not use any deprecated apis as far as I'm aware, so it should work just fine. If you experience any issues after the upgrade, please let me know. If you depend on any software product, I'd advise you to wait a few weeks and check the internet for others sharing tgeir experiences before upgrading.

**Comment by miletbaker** [comment]
Just confirming - I'm able to use it fine with Sierra. I'll let you know if I experience any issue but so far so good.

**Comment by HendrikNoeller** [comment]
Thanks for the feedback Jon! Have you tried the new "Tabs in all Applications" feature? I'll take your word for it an close this issue for now, so zenashopson gets the word....

**Comment by miletbaker** [comment]
Tabs work fine. You can ctrl-tab to switch between them. Only thing missing is it would be nice to have a keyboard shortcut to create a new document in a new Tab rather than Window. cmd-T would be ideal.

**Comment by HendrikNoeller** [comment]
Great! I'll note that down as a to-do for the next version!

**Comment by HendrikNoeller** [comment]
Hi Jon,

I know it’s been a while, but I only now installed Sierra, since I couldn’t afford any downtime incase of an installation failure during the last few months.
I fiddled around with the new window/new tab thing and came to the conclusion that I’m not going to add a new Tab button. The general best practice seems to be to keep it to a „New“ Button, and respect the preference the user has set in "System Settings → Dock → Prefer Tabs over Windows“. So I decided Writer should do that as well.

Best
Hendrik
