### ISSUE TITLE
All caps are formatted as Character elements

### ISSUE THREAD

**Issue by tenny1028** [HendrikNoeller/Writer#3]
This may or may not be intentional. All caps are live formatted as character elements even when they follow a previous character or parenthesis element.

Since there's already a character to force the character element (`@`), all caps shouldn't force this, unless it's a part of the Fountain language.

![screen shot 2016-04-19 at 12 06 09 am](https://cloud.githubusercontent.com/assets/3422979/14628339/93c780e2-05c2-11e6-9e85-466c22a6a34a.png)

**Comment by HendrikNoeller** [comment]
The fountain standard states that a line of just caps is a character name, because thats the way character names are in screenplays, and fountain is intended to pick the formatting up from you making it look like a screenplay.
However, the standart also states that a character name needs to be preceeded by an empty line. I forgot to implement this little point in live preview, but i have already fixed it in the current development Version, which will be released as 2.1 shortly.

**Comment by tenny1028** [comment]
Closed because it was fixed in commit https://github.com/HendrikNoeller/Writer/commit/19f90d91602eb5128544b23d1718bd41f6a8aea6
